name: "Testing"
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Fetch info about PR"
        env:
          COMMIT_HASH: ${{ github.event.head_commit.id }}
          GH_TOKEN: ${{ github.token }}
        run: |
          author=$(gh pr list --state closed --json author,mergeCommit | jq --arg commit_hash "$COMMIT_HASH" '.[] | select(.mergeCommit.oid == commit_hash) | .author')
          echo "$author"
      - name: "Check stuff"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
