name: "Testing"
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch info about PR"
        env:
          COMMIT_HASH: ${{ github.head_commit.id }}
        run: |
          pr_number=$(gh pr list --state closed --json | jq --arg commit_hash "$COMMIT_HASH" '.[] | select(.mergeCommit.oid == commit_hash)')
          echo $pr_number
      - name: "Check stuff"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
